name: Deploy Stage

on:
  push:
    branches:
      - stage

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Build Angular App
        run: npm run build -- --configuration stage --base-href https://ghumao.demohandler.in/

      - name: Deploy to Hostinger Stage
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_SERVER_STAGE }}
          username: ${{ secrets.FTP_USERNAME_STAGE }}
          password: ${{ secrets.FTP_PASSWORD_STAGE }}
          local-dir: ./dist/ghumao/
          server-dir: ${{ secrets.FTP_REMOTE_PATH_STAGE }}
          port: 21
          protocol: ftp
          delete: true
          exclude: |
            **/.htaccess
